version: "3.9"

services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    image: mecanumbot_camera:humble
    container_name: mecanumbot_camera_ros2

    working_dir: /ws
    stdin_open: true
    tty: true

    volumes:
      - ./src:/ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      # ROS networking
      - ROS_DOMAIN_ID=19
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

      # GUI
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1

    entrypoint: /bin/bash
    command: -c "source /root/.bashrc && sleep infinity"
    ports:
      - "8765:8765"
